[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "14.15.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]
    skipPatterns = ['https://www.google-analytics.com']  

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
  exclude = [
     # By Glob pattern
    '**/kontaktid/kiri-saadetud/.html', '/**/privaatsuspoliitika/.html', '/**/teenusetingimused/.html', '**/404.html', '**/admin.html', '**/offline-plugin-app-shell-fallback.html'
  ]